/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Suprotim
 */
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*; 
public class Staffs_Details extends javax.swing.JFrame {

    /**
     * Creates new form Staffs_Details
     */
    public Staffs_Details() {
        initComponents(); 
        setDefaultCloseOperation(Staffs_Details.DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fetchStaffs = new javax.swing.JButton();
        exitStaffs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 241, 230));
        jTable1.setForeground(new java.awt.Color(1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STAFF ID", "NAME", "CONTACT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        fetchStaffs.setBackground(new java.awt.Color(173, 247, 182));
        fetchStaffs.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fetchStaffs.setText("FETCH");
        fetchStaffs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fetchStaffs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchStaffs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchStaffsActionPerformed(evt);
            }
        });
        getContentPane().add(fetchStaffs, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 289, 90, 40));

        exitStaffs.setBackground(new java.awt.Color(251, 111, 146));
        exitStaffs.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        exitStaffs.setText("EXIT");
        exitStaffs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitStaffs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitStaffs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitStaffsActionPerformed(evt);
            }
        });
        getContentPane().add(exitStaffs, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 289, 81, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 280, 800, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchStaffsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel(); 
        String url="jdbc:mysql://localhost/library";
        String user="root"; 
        String pwd="epikishere12345."; 
        String query="select * from staffs;"; 
        try{ 
            Connection conn = DriverManager.getConnection(url, user, pwd); 
            Statement stm = conn.createStatement(); 
            ResultSet rs = stm.executeQuery(query);
            while (rs.next())
            {
                String staffid=rs.getString("STAFF_ID");
                String name=rs.getString("NAME"); 
                String contact=rs.getString("CONTACT");
                
                model.addRow(new Object[]{staffid,name,contact}); 
            }
            rs.close();
            stm.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
        
    }//GEN-LAST:event_fetchStaffsActionPerformed

    private void exitStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitStaffsActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_exitStaffsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staffs_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staffs_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staffs_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staffs_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staffs_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitStaffs;
    private javax.swing.JButton fetchStaffs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
